### ISSUE TITLE
The mpradio.service fails at start

### ISSUE THREAD

**Issue by Angenios** [morrolinux/mpradio-py#56]
![immagine](https://user-images.githubusercontent.com/37461401/82062914-1995da00-96cb-11ea-8637-ea5f3d37ac27.png)

Honestly, I have no idea on how this works. Or, at least, it is not really user-friendly. I rebooted my pi with an USB plugged in as you say, but after that the service doesn't work anymore. I have connected a wire to GPIO 4 in order to stream via FM, though it simply doesn't work. I have no idea what to do, I don't even know how to disinstall this thing. I admit I'm really ignorant in this matter, so I ask you a bit of help.

**Comment by morrolinux** [comment]
Hi
Can you paste here your pirateradio.conf file?

**Comment by Angenios** [comment]
> 
> 
> Hi
> Can you paste here your pirateradio.conf file?

Hello, thanks for reaching out, here you are:

```
[PIRATERADIO]
frequency=88.5
btGain=1.7
storageGain=1
treble=-6
output=fm
btBoost=false
implementation=pi_fm_adv

[PLAYLIST]
persistentPlaylist=true
resumePlayback=true
shuffle=true 

[RDS]
updateInterval=3
charsJump=6
stationName=MPRadio
rdsPattern=$ARTIST_NAME - $SONG_NAME
```

**Comment by morrolinux** [comment]
looks alright, where is it placed on the filesystem?

**Comment by Angenios** [comment]
> 
> 
> looks alright, where is it placed on the filesystem?

/home/pi/mpradio/install/pirateradio

**Comment by morrolinux** [comment]
That should be moved to /pirateradio/pirateradio.conf

**Comment by Angenios** [comment]
> 
> 
> That should be moved to /pirateradio/pirateradio.conf

Oh my god, it is working! Thank you a lot! I love you!
