### ISSUE TITLE
Stuttering every ~20 seconds on Pi B+ and Pi 3

### ISSUE THREAD

**Issue by dwijenchawra** [morrolinux/mpradio-py#62]
There are stuttering issues with the Pi B+, every 20 ish seconds it loops back about half a second of audio. I will test on a Pi 3 and see whether it is simply low specs. The Pi 3 was on max overclock. Still occurs with the Pi 3, i have tested the pi_fm_adv program separately with no issues, and playing local files also works fine. I have also disabled wifi on the board. Any way I can debug this? Not sure which log file to look at, or if this would be logged at all.

**Comment by morrolinux** [comment]
Hi, this is a bit odd, I'm able to run mpradio-py on a raspberry Pi 1 no problem!
As for debugging: have you tried any of [these?](https://github.com/morrolinux/mpradio-py#debugging--troubleshooting)
Also htop could be useful just to make sure it's actually a CPU issue
